apiVersion: v1
kind: Secret
metadata:
  name: rag-secrets
  namespace: rag-system
type: Opaque
data:
  # Base64 encoded values - replace with your actual encoded keys
  openai-api-key: eW91ci1vcGVuYWktYXBpLWtleS1oZXJl  # "your-openai-api-key-here" in base64
  qdrant-api-key: eW91ci1xZHJhbnQtYXBpLWtleS1oZXJl  # "your-qdrant-api-key-here" in base64
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-config
  namespace: rag-system
data:
  QDRANT_URL: "https://your-cluster-url.qdrant.io:6333"
  PYTHONPATH: "/app"
  # Add other configuration variables as needed
