apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-chatbot
  namespace: rag-system
  labels:
    app: rag-chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rag-chatbot
  template:
    metadata:
      labels:
        app: rag-chatbot
    spec:
      containers:
      - name: rag-chatbot
        image: rag-chatbot:cpu  # Use CPU-optimized image by default
        imagePullPolicy: Never  # For local Minikube development
        ports:
        - containerPort: 8501
          name: http
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: rag-secrets
              key: openai-api-key
        - name: QDRANT_API_KEY
          valueFrom:
            secretKeyRef:
              name: rag-secrets
              key: qdrant-api-key
        envFrom:
        - configMapRef:
            name: rag-config
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: rag-chatbot-service
  namespace: rag-system
  labels:
    app: rag-chatbot
spec:
  ports:
  - port: 8501
    targetPort: 8501
    name: http
  selector:
    app: rag-chatbot
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rag-chatbot-ingress
  namespace: rag-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: rag-chatbot.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rag-chatbot-service
            port:
              number: 8501
